### ISSUE TITLE
Improving guide page

### ISSUE THREAD

**Issue by harshsinghcs** [jaysomani/firstspot#101]
remove this white space and improve it accordingly
![image](https://github.com/jaysomani/firstspot/assets/115187902/3c359f6c-5cdb-4b28-8cf8-597f38230869)

**Comment by harshsinghcs** [comment]
@jaysomani kindly assign this issue to me under SWOC

**Comment by jaysomani** [comment]
Hey @harshsinghcs you can work on this and keep me updated in every 3 days

**Comment by iamrudhresh** [comment]
@jaysomani kindly assign this issue to me under SWOC
