### ISSUE TITLE
[BUG] Inconsistent Alignment of Menu in Navbar across Pages (Home, Blog, Guide)

### ISSUE THREAD

**Issue by AftabMankapure** [jaysomani/firstspot#111]
### Issue Title:
[BUG] Inconsistent Alignment of Menu in Navbar across Pages (Home, Blog, Guide)

### Description:
The alignment of the menu items in the Navbar is inconsistent across different pages of the FirstSpot website. This inconsistency is observed on the "Home," "Blog," and "Guide" pages.

### Steps to Reproduce:
1. Navigate to the "Home" page.
2. Observe the alignment of menu items in the Navbar.
3. Navigate to the "Blog" page.
4. Note any differences in the alignment of the Navbar menu.
5. Navigate to the "Guide" page.
6. Again, observe the alignment of menu items in the Navbar.

### Expected Behavior:
The alignment of the Navbar menu items should be consistent across all pages, maintaining a uniform and visually appealing appearance.

### Screenshots:
 
![image](https://github.com/jaysomani/firstspot/assets/125949765/ca0a6dcb-37c3-43a9-930e-e5dfd22040ad)
![image](https://github.com/jaysomani/firstspot/assets/125949765/22ea9f31-c871-42a0-8df0-c97b09ce7ca2)
![image](https://github.com/jaysomani/firstspot/assets/125949765/8dee18c0-55e6-473b-9840-a75dd9c8fab7)
 
 

### System Configuration:
- **Laptop:** HP Pavilion
- **OS:** Windows 11
- **Browser:** Chrome
- **Version:** 120.0.6099.201

                                                                             **### _Assign me this issue_**

**Comment by AftabMankapure** [comment]
Assign me

**Comment by jaysomani** [comment]
Hey @AftabMankapure you can work on this and keep me updated in every 3 days

**Comment by AftabMankapure** [comment]
iwoc
