### ISSUE TITLE
"Missing 'Confirm Password' Field on Tourist Registration Page"

### ISSUE THREAD

**Issue by Niharika0104** [jaysomani/firstspot#128]
**Describe the problem**
The absence of a "Confirm Password" field is noted. Including this field would not only enhance the user experience but also help users distinguish between the registration and sign-in forms through the presence of password fields.
Additionally, I've observed that the signup button on the registration page and the login button on the login page are not currently aligned at the center.I would like fix that.
Furthermore, I'd like to enhance the UI by adding rounded corners to the fields, creating a transparent aesthetic.
**Describe the solution you'd like**
I plan to incorporate a "confirm password" field, validating that both passwords match. Additionally, I intend to enforce password strength using regex.

<img width="940" alt="tourist" src="https://github.com/jaysomani/firstspot/assets/124892559/d97e690c-9fca-487b-8a2a-b7052968a32f">

**Comment by rishita0205** [comment]
can you assign me this issue under SWOC

**Comment by jaysomani** [comment]
Hey @Niharika0104 you can work on this and keep me updated in every 3 days you are doing this under iwoc or swoc

**Comment by Niharika0104** [comment]
Sure

**Comment by Niharika0104** [comment]
@jaysomani I raised a PR for this issue.Can you please look into it?
#133

**Comment by Niharika0104** [comment]
#133
