### ISSUE TITLE
feat:Adding OAuth(Google ) sign Up with google on registration page

### ISSUE THREAD

**Issue by Niharika0104** [jaysomani/firstspot#132]
**Is your feature request related to a problem? Please describe.**
As part of enhancing our user registration process, we propose the implementation of an OAuth sign-up feature, specifically allowing users to register using their Google credentials.

**Describe the solution you'd like**
Integrate OAuth for Google sign-up to simplify the registration process and improve user experience.

**Describe alternatives you've considered**
I think the proposed resolution would be sufficient.

**Comment by jaysomani** [comment]
Hey @Niharika0104 you can work on this and keep me updated in every 3 days you are working on this under iwoc or swoc

**Comment by Niharika0104** [comment]
Sure

**Comment by Niharika0104** [comment]
Hey,@jaysomani I will add a sign with google button on registration page.You have two registration forms one for login tourist and other is for tourist guide.Should I add sign up with google on both the forms?Also,to work on this I need some npm packages should I install those?
