### ISSUE TITLE
enhance scrollbar

### ISSUE THREAD

**Issue by itsmeabhishek03** [jaysomani/firstspot#15]
hey @jaysomani the scrollbar of the website is currently looking like this -

![image](https://github.com/jaysomani/firstspot/assets/104294494/d6f6126d-9b6e-4c4f-b047-3aa30c89d201)

I can enhance it by adding some style for better user expierence 

here is a demo - https://www.awesomescreenshot.com/video/23659577?key=72cd85aa5de9bab6000c2ff126774031

if you like it. please assign it to me under SWOC.

**Comment by jaysomani** [comment]
hey @itsmeabhishek03 you can work on this. keep me updated in every 3 days so that i can keep track of progress
