### ISSUE TITLE
Design LogIn pages

### ISSUE THREAD

**Issue by pankhuri92** [jaysomani/firstspot#16]
The log in pages as a guide as well as a tourist are not designed. I would like to add some styling to them.

![Screenshot 2023-12-30 232214](https://github.com/jaysomani/firstspot/assets/138357063/9d962529-b4e1-43d6-abd1-f5123db55122)
![Screenshot 2023-12-30 232322](https://github.com/jaysomani/firstspot/assets/138357063/b9439ad3-db36-45f4-8ce0-9f772ece8127)

@jaysomani please assign the issue to me under SWOC'24

**Comment by jaysomani** [comment]
hey  @pankhuri92 you can work on this issue. keep me updated in every 3 days so that i can keep track of progress

**Comment by pankhuri92** [comment]
Yep sure, thank you!

**Comment by pankhuri92** [comment]
Hey @jaysomani, I have done my part. Kindly review and accept my pr.
![Screenshot 2024-01-03 020234](https://github.com/jaysomani/firstspot/assets/138357063/ad053e94-734a-453e-81de-4985d6c5a808)
![Screenshot 2024-01-03 020247](https://github.com/jaysomani/firstspot/assets/138357063/8d0bed91-620f-42a6-a9b4-39fd1dbbc33a)
