### ISSUE TITLE
Guide page bug fix

### ISSUE THREAD

**Issue by Nandini80** [jaysomani/firstspot#17]
Guide page CSS needed to be improved. Also it's height is given a lot due to which there is scrolling bug.

https://github.com/jaysomani/firstspot/assets/121488571/5ae720bf-5ddc-40b4-bc53-cc89b182d31e

**Comment by jaysomani** [comment]
hey @Nandini80 you can work on this issue and keep me updated in every 3 days so that i can keep track of progress
