### ISSUE TITLE
Glitch in the order tours section of the basic UI

### ISSUE THREAD

**Issue by Navya-1212** [jaysomani/firstspot#28]
- Overlap with Homepage: This glitch is causing an undesirable overlap between the order tours section and the homepage.

- Visual Disturbance: The overlapping elements are creating a visual disturbance in the user interface.
![Screenshot 2024-01-02 172735](https://github.com/jaysomani/firstspot/assets/153123905/4b8e39e4-e9ad-4939-a25b-9390c1be7237)

**Comment by jaysomani** [comment]
Hey @Navya-1212 we have kept it overlapping only its a way to design

**Comment by Navya-1212** [comment]
I can improve the UI in some more interesting way of that particular section

**Comment by jaysomani** [comment]
can you just explain more
