### ISSUE TITLE
Add Return Home Section In The Contact Us PAGE

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [jaysomani/firstspot#31]
I Would Like To Add A Return To Home Section In The Contact Us Page

**Comment by Kapileswar-Moharana** [comment]
@jaysomani Assign This Issue To Me Under SWOC

**Comment by jaysomani** [comment]
hey @Kapileswar-Moharana you can work on this issue and give me updates in every 3 days to keep track of progress
