### ISSUE TITLE
Nav-Bar Section Is Not Responsive In The Case Of Phone View

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [jaysomani/firstspot#34]
I would Like To update The Responsiveness of the Nav Bar Section As Because It Is Not Responsive In The Case Of Phone View

**Comment by Kapileswar-Moharana** [comment]
@jaysomani Assign This Issue To Me Under SWOC

**Comment by Akshayasri0805** [comment]
@jaysomani  please assign me this issue

**Comment by Akshayasri0805** [comment]
@jaysomani  , I have made the nav bar responsive for mobile phones also , and please assign me the project

![Screenshot (217)](https://github.com/jaysomani/firstspot/assets/126628691/afb261fa-d71d-410b-80df-c5f0a2c89c73)

**Comment by brobengali** [comment]
https://clipchamp.com/watch/VMhTfOKBLGZ

assign the issue  to me @jaysomani
