### ISSUE TITLE
css issue in homepage

### ISSUE THREAD

**Issue by jaysomani** [jaysomani/firstspot#4]
the get in touch button is misplaced from its location 

![image](https://user-images.githubusercontent.com/69755312/195250163-e8e8a205-7a9d-4d46-8432-6992b7670406.png)

**Comment by sidharth2829** [comment]
Hello @jaysomani , can u assign this issue to me.

**Comment by SadanandMiskin** [comment]
hello @jaysomani , I would like to solve this issue under SWOC'24, can you please assign it

**Comment by jaysomani** [comment]
hey @sidharth2829 you can work on this keep me updated in every 3 days to track the progress

**Comment by sidharth2829** [comment]
@jaysomani, is this alignment correct?

<img width="1436" alt="Screenshot 2024-01-05 at 7 40 58 PM" src="https://github.com/jaysomani/firstspot/assets/111569459/7b76ed46-269c-466e-b203-683882cdfda8">

**Comment by jaysomani** [comment]
It should be aligned exactly below E of Explore
