### ISSUE TITLE
Notification for Incomplete Sign In Details

### ISSUE THREAD

**Issue by VinayCheripally** [jaysomani/firstspot#43]
https://github.com/jaysomani/firstspot/assets/114852793/2ed467e4-4eeb-4edc-9732-e3df66a0373f

To enhance user experience and improve the formality of the process, consider implementing a notification system when a user clicks the "Sign In" button without entering a username and password.

**Comment by VinayCheripally** [comment]
@jaysomani I would like to work on this task. Kindly assign it to me under SWOC'24.
Thank You!

**Comment by jaysomani** [comment]
Hey @VinayCheripally you can work on this and keep me updated in every 3 days

**Comment by VinayCheripally** [comment]
https://github.com/jaysomani/firstspot/assets/114852793/c6dca07c-c66f-42e4-bf73-9349dc7af91d

I have changed the login.html and made a popup message for no username or password

**Comment by VinayCheripally** [comment]
https://github.com/jaysomani/firstspot/assets/114852793/36f41264-2a4c-4c2e-9e27-12ce49a19a33

I have changed login.html and made pop up msg whenever there is no username or password from user
