### ISSUE TITLE
In filter.html file pune , kolkata and kolapur have wrong images.

### ISSUE THREAD

**Issue by Raunak-Srivastava** [jaysomani/firstspot#51]
Hey @jaysomani @stharanzn... 
Can you please assign this issue to me under SWOC.

**Comment by jaysomani** [comment]
Hey @Raunak-Srivastava you can work on this and keep me updated in every 3 days

**Comment by Raunak-Srivastava** [comment]
I have done all the necessary changes. Please merge my pull request #58 @jaysomani
