### ISSUE TITLE
Enhance Navbar Dropdown Appearance

### ISSUE THREAD

**Issue by Prutha-Upadhyay** [jaysomani/firstspot#56]
I want to refine login and signup dropdowns in the navbar for a more visually appealing and user-friendly interface.

![Screenshot 2024-01-05 225256](https://github.com/jaysomani/firstspot/assets/120392487/4bb1c7a4-0db4-47d8-950e-70a43498f6fa)

@jaysomani Please assign me this issue under SWOC!!!

**Comment by jaysomani** [comment]
Hey @Prutha-Upadhyay you can work on this and keep me updated in every 3 days
