### ISSUE TITLE
Css Styling Improvement

### ISSUE THREAD

**Issue by Suhani2804** [jaysomani/firstspot#7]
![css issue](https://github.com/jaysomani/firstspot/assets/133562522/2275ac36-020f-44d5-b891-89dae2688764)
On this page if the CSS is enhanced a bit it will add to the beauty of the whole website. I would like to work on this issue under SWOC and I am confident that I will be able to work on this issue. Kindly assign it to me.
Waiting for your response. @jaysomani 
Thank you so much!

**Comment by jaysomani** [comment]
Hey @Suhani2804  thank you for showing interest in the enhancement of this project. you can go ahead and work on this and keep me updated in every 3 days so that i can keep track of the progress. :)

**Comment by Suhani2804** [comment]
Thankyou so much sir!

**Comment by krishnagitcontri** [comment]
@jaysomani i would also like to solve this issue can i work?

**Comment by jaysomani** [comment]
Hey @Suhani2804 is their any update ?

**Comment by jaysomani** [comment]
@krishnagitcontri we assign issues on the first come basis

**Comment by Suhani2804** [comment]
Yes sir..I have centered the search bar and the filters and along with that i have done the styling of these elements. I have added some effects on hover for cards and I am working on how to improve the styling of the cards a bit more.
Regards

**Comment by kamalsritha** [comment]
can you please assign me this issue under SWOC.
