### ISSUE TITLE
Fix Typo in Tours page

### ISSUE THREAD

**Issue by rishicds** [jaysomani/firstspot#77]
![Screenshot_2024-01-08-00-36-44-78_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/jaysomani/firstspot/assets/124495375/45932247-594b-4442-9741-370e0965a259)

There is a typo in Other Tours page.
The Search spelling is wrong.
I can fix it.
Please assign it to me under SWOC'24

**Comment by jaysomani** [comment]
Hey we have fixed this already it will display as the new version releases
