### ISSUE TITLE
Feature: add codeql workflow for javascript

### ISSUE THREAD

**Issue by harmeetsingh11** [jaysomani/firstspot#83]
### Is your feature request related to a problem? Please describe. 

The repository contains code in `javascript`, it does not have workflow for code scanning. 

### Describe the solution you'd like 

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by jaysomani** [comment]
Hey @harmeetsingh11 you can work on this issue and keep me updated in every 3 days
