### ISSUE TITLE
Create Contributing.md for contributers

### ISSUE THREAD

**Issue by jaysomani** [jaysomani/firstspot#88]

**Comment by PRASUN-SITAULA** [comment]
Hey, @jaysomani, can I work on this issue?

**Comment by Bhupendra3444** [comment]
hey @jaysomani Please assign me this task under iwoc. I want to work on it.

**Comment by Sakshamjain98** [comment]
@jaysomani  Sir I want to work on this issue please assign it to me

**Comment by Sakshamjain98** [comment]
hey @jaysomani Please assign me this task under iwoc. I want to work on it.

**Comment by Er-luffy-D** [comment]
hey @jaysomani, Can I work on this issue under iwoc24?

**Comment by raysofani** [comment]
Hello @jaysomani please assign this issue to me under IWOC2024.

**Comment by jaysomani** [comment]
Hey @PRASUN-SITAULA you can work on this and keep me updated in every 3 days

**Comment by PRASUN-SITAULA** [comment]
@jaysomani can I give your email as repository maintainer in CODE_OF_CONDUCT.md file?

**Comment by PRASUN-SITAULA** [comment]
@jaysomani, you merged the contributing file from the person who was not assigned for creating the contributing.md file.
