### ISSUE TITLE
Create a blog section where guide can write blogs about tourist destinations and more

### ISSUE THREAD

**Issue by jaysomani** [jaysomani/firstspot#91]

**Comment by shivam101203** [comment]
please asign me this issue under iwoc

**Comment by shivam101203** [comment]
@jaysomani

**Comment by jaysomani** [comment]
Hey @shivam101203 you can work on this and keep me updated in every 3 days

**Comment by shivam101203** [comment]
Okk sir

**Comment by shivam101203** [comment]
Sorry sir but due to my mistake assignment have been removed

**Comment by shivam101203** [comment]
I will do it right now not gonna go for 3 days

**Comment by shivam101203** [comment]
Please reassign it to me

**Comment by jaysomani** [comment]
Done @shivam101203

**Comment by shivam101203** [comment]
Okk sir

**Comment by shivam101203** [comment]
Sir please merge if correct

**Comment by shivam101203** [comment]
sir please accept #106  as merge

**Comment by shivam101203** [comment]
Please close this issue so that I could get a point

**Comment by shivam101203** [comment]
In iwoc @jaysomani

**Comment by shivam101203** [comment]
Please close this issue so that I could get points in the iwoc 24 @jaysomani  please do it fast iwant to contribute more
