### ISSUE TITLE
[ Feat ] : Navbar and Footer Improvement and Theme Color Change

### ISSUE THREAD

**Issue by AftabMankapure** [jaysomani/firstspot#98]
Issue Title:
Navbar and Footer Improvement and Theme Color Change

1. Bug Description:
The current navbar and footer on the FirstSpot website have certain design aspects that could be enhanced for better user experience and aesthetics.

2. How to Reproduce Issue:
        1. Open the home page o of FirstSpot 
        
3. Describe Expected Behavior:
Improved design for the navbar and footer, providing a more user-friendly and visually appealing layout. Additionally, a change in the theme color to enhance overall website aesthetics.

4. Screenshots or Video:
    Navbar :
![image](https://github.com/jaysomani/firstspot/assets/125949765/e23142cf-9a1c-49d2-8e82-2abfcabbc3d8)
   Footer :
 
![image](https://github.com/jaysomani/firstspot/assets/125949765/7b8733c2-338a-4350-910d-e0085b7f1fd8)

5. System Configuration: 
          Laptop: HP Pavilion  
          OS: Windows 11
         Browser: Chrome
         Version: 120.0.6099.201

**Comment by AftabMankapure** [comment]
Assign me this issues

**Comment by jaysomani** [comment]
Hey @AftabMankapure someone is working on this issue already please look at different issue
