### ISSUE TITLE
[BUG]:  Navigation Issue - Unable to Visit from Blog to Home

### ISSUE THREAD

**Issue by AftabMankapure** [jaysomani/firstspot#99]
Title: 
         Navigation Issue - Unable to Visit from Blog to Home

1. Description:
      There is an issue with the navigation flow on the FirstSpot website, specifically when attempting to navigate from the "blog" page 
      to the "home" page. Following the usual navigation steps results in an error or unexpected behavior, preventing users from 
      seamlessly moving between these two essential pages.

2. Steps to Reproduce:
           1. Go to the "blog" page.
          2. Attempt to navigate to the "home" page.

3.  Screenshots or Video:
![image](https://github.com/jaysomani/firstspot/assets/125949765/6b56599c-4f00-4fae-9609-0be57363a5f7)
Click on home option 
![image](https://github.com/jaysomani/firstspot/assets/125949765/6ec8a14c-e7b5-49d0-804a-ace042390cd2)

4. System Configuration:
         Laptop: HP Pavilion
        OS: Windows 11
        Browser: Chrome
        Version: 120.0.6099.201
Assign me this issue

**Comment by harshsinghcs** [comment]
@AftabMankapure will you work on it?

**Comment by harshsinghcs** [comment]
after being assigned?

**Comment by AftabMankapure** [comment]
Yes assign me under JWOC or IWOC

**Comment by jaysomani** [comment]
Hey @AftabMankapure You can work on this and keep me updated in every 3 days

**Comment by shivam101203** [comment]
Please assign me issue under iwoc
@jaysomani

**Comment by AftabMankapure** [comment]
Add JWoC'24 label

**Comment by AftabMankapure** [comment]
some one change the blog page 
from 
![image](https://github.com/jaysomani/firstspot/assets/125949765/6c5913bb-65e9-4620-9dc8-19daaf301a5d)

to 
their is no nav bar 
![image](https://github.com/jaysomani/firstspot/assets/125949765/47e3b928-d30c-410e-9dc1-7c794db68a86)
